kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

markdown:
  kramdown

baseurl: /grpc.github.io

githuburl: https://github.com/grpc/grpc.github.io/

sass:
  style: compressed
  
paginate: 5

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->
