kramdown:
  input: GFM
  hard_wrap: false

markdown:
  kramdown

baseurl: /grpc.github.io

githuburl: https://github.com/grpc/grpc.github.io/

sass:
  style: compressed
  
paginate: 2

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

exclude: [vendor]
