kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

markdown:
  kramdown

baseurl:

githuburl: https://github.com/grpc/grpc.github.io/

sass:
  style: compressed
  
plugins: [jekyll-paginate]
  
paginate: 5

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->
