baseURL = "https://cjyabraham.github.io/"
languageCode = "en-us"
title = "gRPC"
pygmentsCodeFences = true

[params]
	grpc_release_tag = "v1.19.0"
	grpc_java_release_tag = "v1.20.0"
	milestones_link = "https://github.com/grpc/grpc/milestones"
